### ISSUE TITLE
wrong default interval in README and docs

### ISSUE THREAD

**Issue by magnattic** [upsidr/merge-gatekeeper#34]
Docs and readme say that the default interval is 30 seconds, but in the code it's 5. Would be cool if the docs could be updated. :)

Also, I just want to say how big of a help this action is for us. We are using it together with the GH merge queue to finally set up the workflow how we need it. Thank you for creating this! We were almost ready to leave Github Actions behind because of this feature missing.

**Comment by rytswd** [comment]
Hi @magnattic - thanks for raising this! Apologies how it completely slipped our mind - this will be fixed with #35 👍
(I'll just wait another pair of eyes to review the change details, just in case before merging this.)

Great to hear that you are finding this solution useful, please do not hesitate to raise any issues or ideas ☺️
